- name: Install uv
  uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
  with:
    enable-cache: true
    cache-dependency-glob: "uv.lock"

- name: Install GDAL
  run: |
    sudo apt-get update -qy
    sudo apt-get install -qy -o APT::Install-Suggests=false libgdal-dev gdal-bin

- name: Install pre-commit hooks
  run: uv run pre-commit install
